const PADDING_LEFT = 2;
const PADDING_LEFT_STRING = " ".repeat(PADDING_LEFT);

const PADDING_RIGHT = 3;
const PADDING_RIGHT_STRING = " ".repeat(PADDING_RIGHT);

export {
  PADDING_LEFT,
  PADDING_LEFT_STRING,
  PADDING_RIGHT,
  PADDING_RIGHT_STRING,
};
